<template>
    <div>
        <h1>Reporting resources</h1>
        <div>
            <div v-for="category in data" class="category">
                <h2>{{ category.title }}</h2>
                <div v-for="item in category.list">
                    <h3>{{ item.title }}</h3>
                    <p>{{ item.desc }}</p>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup lang="ts">
const data = [
    {
        title: 'removable offenses',
        list: [
            {
                title: 'Hate speech and symbols',
                desc: 'Any form of communication that promotes or incites hatred, violence, discrimination, or hostility towards groups based on attributes such as race, ethnicity, nationality, religion, gender, sexual orientation, disability, or other characteristics. Please note that we distinguish between antisemitism and anti-zionism.'
            },
            {
                title: 'Misinformation & propaganda',
                desc: 'False or inaccurate information that is spread. It can be created and disseminated through various mediums such as social media and news outlets.'
            },
            {
                title: 'Spam & bot content',
                desc: 'Content that is not related to the struggle for Palestinian liberation and/or is generated by a computer programs rather than human beings.'
            },
            {
                title: 'Threats of violence',
                desc: 'Every social media account in our database.'
            }
        ]
    },
    {
        title: 'we do not remove resources due to:',
        list: [
            {
                title: 'Anti-zionism',
                desc: `We wholeheartedly support our Jewish community and recognize the very real existence of antisemitism. It's crucial to distinguish between anti-zionism and antisemitism, especially considering that Palestinians are also Semitic people.`
            },
            {
                title: 'Policy disagreement',
                desc: 'Policy disagreement is not grounds for content removal from a site because it\'s important to uphold principles of free expression and diverse perspectives. Content should be evaluated based on its adherence to community guidelines and legal standards rather than simply differing opinions or ideologies.'
            },
            {
                title: 'Criticism of governments and officials',
                desc: 'Speaking truth to power is a core principle of our work, and as such, criticisms of governments and their officials are not worthy of removal.'
            },
            {
                title: 'Respectful discourse',
                desc: 'Every social media account in our database'
            },
            {
                title: `I just don't like it`,
                desc: 'Although we acknowledge that many resources cover uncomfortable topics like systemic violence, death, and prejudice, we do not remove them for causing discomfort. However, if a resource contains legitimate issues such as threats of violence against individuals or genocidal intent, please inform us.'
            }
        ]
    }
]
</script>

<style scoped>
h1 {
    font-size: 24px;
    margin-bottom: 66px;
}

h1 + div {
    row-gap: 32px;
}

.category {
    row-gap: 16px;
}

h2 {
    color: var(--color-gray-2);
    font-size: 12px;
    letter-spacing: 0.1em;
    text-transform: uppercase;
}

p {
    color: var(--color-gray-0);
    margin-top: 4px;
}
</style>